In [2]:
import numpy as np 
import pandas as pd
from sklearn import datasets 
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [3]:
df=datasets.load_wine()

In [4]:
x=df.data

In [5]:
y=df.target

In [6]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.24,random_state=5)

In [7]:
GNB = GaussianNB()
GNB.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [8]:
print('training accuracy:',GNB.score(x_train,y_train)*100,'%')

training accuracy: 99.25925925925925 %


In [12]:
y_predictions = GNB.predict(x_test)

In [13]:
print('testing accuracy:',GNB.score(x_test,y_test)*100,'%')

testing accuracy: 93.02325581395348 %


In [14]:
y_test

array([0, 1, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 2, 1, 2, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 2, 2, 0, 1, 1, 0, 0, 2, 2, 0, 2, 2, 1, 1, 1, 2])

In [15]:
y_predictions

array([0, 1, 0, 0, 2, 2, 0, 0, 1, 1, 0, 0, 2, 1, 2, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 2, 2, 0, 1, 1, 0, 0, 2, 2, 0, 2, 2, 1, 1, 1, 2])

In [16]:
y_prba = GNB.predict_proba(x_test)

In [17]:
y_prba

array([[9.99997175e-01, 2.82482825e-06, 1.59430257e-32],
       [1.57420979e-01, 8.42579021e-01, 5.24714063e-31],
       [1.00000000e+00, 4.79234397e-21, 6.59974595e-48],
       [1.00000000e+00, 2.38748731e-11, 2.08799633e-30],
       [7.01027439e-23, 2.77402829e-07, 9.99999723e-01],
       [2.10736731e-20, 5.03651149e-22, 1.00000000e+00],
       [1.00000000e+00, 3.28030966e-11, 4.96204882e-26],
       [9.99999917e-01, 8.28846606e-08, 5.59333944e-33],
       [6.21989198e-05, 9.99937801e-01, 8.56571558e-23],
       [8.69552744e-04, 9.99130447e-01, 1.11853398e-23],
       [9.99983841e-01, 1.61585362e-05, 2.33784880e-29],
       [1.00000000e+00, 1.40511358e-10, 4.20374358e-27],
       [7.99250399e-18, 1.07429998e-04, 9.99892570e-01],
       [8.11198799e-12, 1.00000000e+00, 3.66738162e-10],
       [8.20264250e-20, 3.92718667e-04, 9.99607281e-01],
       [9.99999993e-01, 7.24184057e-09, 1.53231979e-29],
       [7.91495599e-08, 9.99999921e-01, 9.80067347e-21],
       [8.73910916e-02, 9.12608